// Copyright (c) <YEAR> <COPYRIGHT HOLDER>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

namespace StrideAssetStore.Core.Models;

/// <summary>
/// Aggregate generated by CI and consumed by the app. See <c>schemas/index-lock.schema.json</c>.
/// </summary>
public sealed record IndexLock
{
    public int SchemaVersion { get; init; } = 1;

    /// <summary>ISO-8601 timestamp, set by the generator (kept as a string for determinism).</summary>
    public required string GeneratedAt { get; init; }

    public IReadOnlyList<IndexedAsset> Assets { get; init; } = [];
}

/// <summary>A single asset entry in the aggregated index.</summary>
public sealed record IndexedAsset
{
    public required string Id { get; init; }

    public required string Repo { get; init; }

    public required AssetManifest Manifest { get; init; }

    /// <summary>GitHub stargazer count, when known (filled by the bot via the GitHub API).</summary>
    public int? Stars { get; init; }

    /// <summary>GitHub fork count, when known. Comes from the same API call as <see cref="Stars"/>,
    /// and says something stars don't: how many people took the asset somewhere of their own.</summary>
    public int? Forks { get; init; }

    /// <summary>Rolling daily history of <see cref="Stars"/> (carried over from the previous index,
    /// ~30 days) — enables the "trending" sort (7-day star delta) with zero server.</summary>
    public IReadOnlyList<StarsSnapshot> StarsSnapshots { get; init; } = [];

    /// <summary>ISO-8601 committer date of the commit that created this asset's registry entry
    /// ("new arrivals" sort), or null when the registry checkout is shallow.</summary>
    public string? AddedAt { get; init; }

    /// <summary>Deprecation marker carried over from the registry entry.</summary>
    public DeprecationInfo? Deprecated { get; init; }

    public required IndexedVersion Latest { get; init; }

    /// <summary>Released versions discovered from the repo's git tags (author-controlled).</summary>
    public IReadOnlyList<IndexedTagVersion> Versions { get; init; } = [];

    public IReadOnlyList<IndexedCertifiedVersion> Certified { get; init; } = [];

    /// <summary>One of: ok, warning, error, unavailable.</summary>
    public required string ValidationStatus { get; init; }

    public IReadOnlyList<string> ValidationMessages { get; init; } = [];

    public string? LastValidatedAt { get; init; }
}

/// <summary>The enriched, validated <c>latest</c> version of an asset.</summary>
public sealed record IndexedVersion
{
    public required string Ref { get; init; }

    public required string Commit { get; init; }

    /// <summary>Deterministic SHA-256 of the AssetData/ folder.</summary>
    public required string ContentHash { get; init; }

    /// <summary>Detected from the .csproj (Stride.* PackageReference), or null.</summary>
    public string? DetectedStrideVersion { get; init; }

    /// <summary>Target framework(s) read from the .csproj (e.g. net10.0), or null.</summary>
    public string? TargetFramework { get; init; }

    /// <summary>NuGet packages the project references (external dependencies, not store assets).</summary>
    public IReadOnlyList<IndexedPackage> ExternalDependencies { get; init; } = [];

    /// <summary>Directly declared/detected store dependency ids (before transitive resolution). Persisted
    /// so an incremental rebuild can re-resolve reused assets from real direct edges, not a stale closure.</summary>
    public IReadOnlyList<string> DirectDependencies { get; init; } = [];

    /// <summary>Transitive set of resolved dependency ids (deduplicated, cycle-free).</summary>
    public IReadOnlyList<string> ResolvedDependencies { get; init; } = [];

    /// <summary>ISO-8601 committer date of <see cref="Commit"/> (for recency sorting), or null.</summary>
    public string? CommittedAt { get; init; }

    public long SizeBytes { get; init; }

    /// <summary>The files under <c>AssetData/</c> at <see cref="Commit"/> (relative forward-slash
    /// paths). Precomputed by the indexer so the storefront's file viewer doesn't have to call the
    /// GitHub API (60 req/h/IP anonymous) on every detail-page visit.</summary>
    public IReadOnlyList<IndexedFile> Files { get; init; } = [];
}

/// <summary>One file of an indexed version's AssetData/ tree.</summary>
public sealed record IndexedFile
{
    public required string Path { get; init; }

    public long SizeBytes { get; init; }
}

/// <summary>One day's stargazer count (dates are "yyyy-MM-dd" — lexicographically ordered).</summary>
public sealed record StarsSnapshot
{
    public required string Date { get; init; }

    public int Stars { get; init; }
}

/// <summary>A NuGet package the asset references (its external dependency).</summary>
public sealed record IndexedPackage
{
    public required string Name { get; init; }

    public string? Version { get; init; }
}

/// <summary>A released version discovered from a git tag (lightweight: tag → commit).</summary>
public sealed record IndexedTagVersion
{
    /// <summary>Human version label (tag without a leading 'v').</summary>
    public required string Version { get; init; }

    public required string Tag { get; init; }

    public required string Commit { get; init; }
}

/// <summary>A certified version — an immutable, maintainer-approved commit pin.</summary>
public sealed record IndexedCertifiedVersion
{
    public required string Version { get; init; }

    public string? Tag { get; init; }

    public required string Commit { get; init; }

    public string? CertifiedBy { get; init; }

    public string? CertifiedAt { get; init; }
}
